### ISSUE TITLE
Binding port to other one rather than 27017 and IP to 0.0.0.0

### ISSUE THREAD

**Issue by weiwurw** [themattman/mongodb-raspberrypi-docker#10]
Hi,

I am new to mongodb and now i am running your 7.0.5 in my raspberry pi 4 with ubuntu server but when i pass the --bind_ip or -p, the docker container will quit immediate now i am running it with: docker run --name letimongo -d -v mymongodata:/data/db mongodb-raspberrypi4-unofficial-r7.0.5 --auth, how can i change the ip to 0.0.0.0 so I can access it through remote server? 

I tried to find the mongo configuration file but not finding it. 

All best,

Wei

**Comment by themattman** [comment]
I would recommend looking on stackoverflow or forums.mongodb.com for user issues with MongoDB. This repo is dedicated to the functioning of docker images.

**Comment by themattman** [comment]
Did you try to look at the logs from `mongod`? That might give some insight as to what you are seeing and why.

**Comment by Serpensin** [comment]
Why not simply do `-p 1337:27017`? This maps the port 1337 on your host to the port 27017 inside the container.
