### ISSUE TITLE
Can i use the MONGO_INIT env variables to create a database and a user with password?

### ISSUE THREAD

**Issue by Fynnyx** [themattman/mongodb-raspberrypi-docker#14]
I was setting up the container but I think it doesn't create the user. I used the env variables from the official docker image.
And I cant find the db aswell.

do they work in this image aswell?

**Comment by Fynnyx** [comment]
The user works now but the database isnt created. Whats the way to go?

**Comment by themattman** [comment]
Does this help?
https://docs.linuxserver.io/general/understanding-puid-and-pgid/
