### ISSUE TITLE
Use this on docker-compose

### ISSUE THREAD

**Issue by jasonbrianrivero** [themattman/mongodb-raspberrypi-docker#16]
Hello!

How can I use this on docker-compose?

I am getting an issue where: 
Pulling filecloud.mongodb (themattman/mongodb-raspberrypi-docker:r7.0.5-mongodb-raspberrypi-docker-unofficial)...
ERROR: pull access denied for themattman/mongodb-raspberrypi-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by themattman** [comment]
Duplicate of #4.
