### ISSUE TITLE
no assets for release 7.0.8

### ISSUE THREAD

**Issue by rburgst** [themattman/mongodb-raspberrypi-docker#17]
the release for 7.0.8 does not have assets associated, which makes it impossible to install that version.

**Comment by themattman** [comment]
Thanks for reporting. The [7.0.7 release](https://github.com/themattman/mongodb-raspberrypi-docker/releases/tag/r7.0.7-mongodb-raspberrypi-docker-unofficial) has assets in the meantime. I'll dig into this in the next few days and try to get it up.

**Comment by themattman** [comment]
Done. And the 7.0.11 release is in the oven and building at the moment.
