### ISSUE TITLE
Update docker image to 7.0.11?

### ISSUE THREAD

**Issue by starapo7348** [themattman/mongodb-raspberrypi-docker#18]
The binary for the Docker image for MongoDB V7.0.11 is available.

Do you plan an update of the mongodb-raspberrypi-docker image to 7.0.11 as well?

The last update 7.0.8 is dated April 23th.

Thank you for your work.

**Comment by themattman** [comment]
Hi @starapo7348, yes I plan to update the docker image soon. My automation ran into issues and I haven't found the time to look into it. I plan to release newer v7.0 binaries as well too.

**Comment by themattman** [comment]
Note that a couple of the v7.0 releases were [cancelled](https://www.mongodb.com/docs/upcoming/release-notes/7.0/). I have the latest [7.0.14 binaries](https://github.com/themattman/mongodb-raspberrypi-binaries/releases/tag/r7.0.14-rpi-unofficial) up for the Pi4, and once the Pi5 binaries are finished building the docker image should get published. Expect this to take about a day.

**Comment by themattman** [comment]
The [7.0.14 image](https://github.com/themattman/mongodb-raspberrypi-docker/releases/tag/r7.0.14-mongodb-raspberrypi-docker-unofficial) is published. Closing this out.
