### ISSUE TITLE
Remove "$" sign from commands in readme

### ISSUE THREAD

**Issue by isaric** [themattman/mongodb-raspberrypi-docker#5]
The commands have a nice copy button next to them but they will fail because the dollar sign is at the beginning of each command.

I understand this was meant to simulate the shell but it makes copying and using the command a little harder.

Please consider removing the dollar sign.

**Comment by themattman** [comment]
Thanks for the feedback, I'll consider making changes to the README.

That's a convention I've always followed to make it clear to users that the text is intended for a command line. It has the added benefit of ensuring that copied text isn't immediately executed and allows the user to modify before executing. This can be beneficial if the text is either incorrectly copied, or if something else is amiss that would cause issues to the user's environment. I admit that it does add friction.

**Comment by themattman** [comment]
I struck a balance by keeping the `$` prompt string in some cases to differentiate from user input to command output. Other prompts that were solely user input, I removed the prompt string to enable easier copying (e.g. the `wget` command).
