### ISSUE TITLE
[Bug] tarball of 7.0.4 release is corrupt

### ISSUE THREAD

**Issue by DeadlyFirex** [themattman/mongodb-raspberrypi-docker#7]
Hey there, 
First of all, thank you for your work, I appreciate it!

It seems that your latest `7.0.4` [release](https://github.com/themattman/mongodb-raspberrypi-docker/releases/tag/r7.0.4-mongodb-raspberrypi-docker-unofficial) is corrupt, as the provided tarball contains seemingly only 20 bytes of garbo data, which obviously shouldn't and doesn't work.

I hope you have a nice day otherwise.

**Comment by themattman** [comment]
You are correct, that doesn't look right. Likely a bug in the automation. I'll check the logs and see what happened. I should have an updated release up later this week.

Thanks for reporting this.

**Comment by DeadlyFirex** [comment]
Thanks a ton, please let me know when you update the release so that I can test it, and so that we can close the issue!

**Comment by themattman** [comment]
Sorry for the delay, it has been a busy few weeks at MongoDB and in life. The release has been updated, it was indeed a bug in my automation. Now that `7.0.5` has [been cut](https://github.com/mongodb/mongo/releases/tag/r7.0.5), there should be a new release available here in the coming days for that as well. Let me know if you run into any problems with `7.0.4` and I can take a look.
